apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-prometheus-to-read-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader 
subjects:
- kind: ServiceAccount
  name: prometheus-k8s    
  namespace: monitoring   