{
 "title": "Custom-Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ec2_instances_created_total (counter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ec2_instances_created_total{job=\"$job\", namespace=\"$namespace\"}) by (instance, pod)"
    }
   ]
  },
  {
   "title": "ec2_instances_deleted_total (counter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ec2_instances_deleted_total{job=\"$job\", namespace=\"$namespace\"}) by (instance, pod)"
    }
   ]
  },
  {
   "title": "ec2_instances_replaced_total (counter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ec2_instances_replaced_total{job=\"$job\", namespace=\"$namespace\"}) by (instance, pod)"
    }
   ]
  },
  {
   "title": "ec2_operation_errors_total (counter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ec2_operation_errors_total{job=\"$job\", namespace=\"$namespace\"}) by (instance, pod)"
    }
   ]
  },
  {
   "title": "ec2_instance_running (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ec2_instance_running{job=\"$job\", namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}